packages:
  - config
  - packages/*
  - test

catalogs:
  prisma:
    "@prisma/prisma-schema-wasm": 7.10.0-2.d0368e25c88e68caa4d283b5f2d88d1b76ed9356
  tree-sitter:
    web-tree-sitter: 0.27.0
  samchon:
    tstl: ^3.0.0
    "@nestia/e2e": ^13.0.2
    typia: &typia ^15.1.0
    "@typia/interface": *typia
    "@typia/utils": *typia
  typescript:
    ttsc: &ttsc ^0.30.1
    "@ttsc/evidence": *ttsc
    "@ttsc/lint": *ttsc
    typescript: ^7.0.2
    prettier: ^3.9.6
  utils:
    "@types/node": ^22.20.2
    bumpp: ^12.3.0
    rimraf: ^6.1.3
    yaml: ^2.9.0
